import Link from 'next/link'
import PreviewBanner from '@/components/ata/PreviewBanner'

const links = [
  ['Homepage','/'],['Flagship tour','/tours/flagship-preview'],['Customer request flow','/tours/flagship-preview#request'],['Owner overview','/ata-admin'],['Tour editor','/ata-admin#tours'],['Pricing editor','/ata-admin#pricing'],['Dates and availability','/ata-admin#pricing'],['Verification and release','/ata-admin#verification'],['Customer workflow','/ata-admin#customer-requests'],
]
export const metadata={title:'ATA visual review guide',robots:{index:false,follow:false}}
export default function ReviewPage(){return <main className="min-h-screen bg-[#f4f1e9] text-[#17393b]"><PreviewBanner/><header className="bg-[#0b3032] px-5 py-20 text-white"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#f3cb7a]">ATA owner review</p><h1 className="mt-5 max-w-4xl font-serif text-6xl leading-none">See the website and owner operation working together.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">This review uses demonstration information. It does not publish content, take payment, confirm bookings or change ATA’s live systems.</p></div></header><div className="mx-auto max-w-5xl px-5 py-16"><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{links.map(([label,href],i)=><Link key={label} href={href} className="group rounded-2xl border border-[#17393b]/15 bg-white p-6 shadow-sm hover:-translate-y-1 hover:shadow-lg focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#a3482e]"><span className="text-xs font-bold text-[#a3482e]">0{i+1}</span><h2 className="mt-7 font-serif text-2xl">{label}</h2><p className="mt-4 text-sm font-bold">Open preview →</p></Link>)}</section><section className="mt-14 grid gap-8 rounded-3xl bg-white p-7 lg:grid-cols-2 lg:p-10"><div><h2 className="font-serif text-3xl">What ATA will control</h2><ul className="mt-5 space-y-3 text-sm leading-6">{['Tour wording and important information','Prices, dates and availability','Evidence review and business approval','Separate public release','Customer requests, quotes and manual confirmation','User roles and activity history'].map(x=><li key={x}>✓ {x}</li>)}</ul></div><div><h2 className="font-serif text-3xl">Questions for this review</h2><ol className="mt-5 space-y-3 text-sm leading-6">{['Does the public experience feel recognisably ATA?','Can an owner understand what needs attention?','Are the price and date placeholders clear?','Is the difference between approval and release clear?','Is manual confirmation unmistakable?','What information should ATA provide next?'].map((x,i)=><li key={x}><b>{i+1}.</b> {x}</li>)}</ol></div></section></div></main>}

